version: "3"

services:
  webserver:
    build:
      context: webserver
    image: root/gigatester-webserver
    ports:
      - "80:8000"
    environment:
      - SECRET='eb8d5498f143d53df55ce37fb3d944a3076f757b1268bfb4ce54959f3c2b5c1d'
      - MAX_QUEUE=350
      - MAX_REG=5
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: 500M
    volumes:
      - './queue:/queue'
      - './webserver:/prog'

